FROM python:3.13.3-slim-bookworm

WORKDIR /usr/src/app

COPY ./credentials.json /usr/src/app/credentials.json
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV GOOGLE_APPLICATION_CREDENTIALS="/usr/src/app/credentials.json"



RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .
